### ISSUE TITLE
consider formalize the package

### ISSUE THREAD

**Issue by tqchen** [yanqingmen/xgboost4j#1]
Hi @yanqingmen  I just saw this package and this seems interesting to make xgboost available to jvm community.

Would you be interested in trying to formalize the package and contribute back to xgboost main repo?

Currently the port was build on swig, would be great to have a pure JNI based version that wraps the xgboost_wrapper and handles the callings

**Comment by yanqingmen** [comment]
hi, @tqchen 

I'd be very glad to contribute to xgboost. I've learned a lot from this tool. 
It may be time consume for me to make a pure JNI based wrapper since I used to build wrapper via swig. But I will try my best to do this.

thanks a lot for such a great tool~

**Comment by tqchen** [comment]
great, thanks! I think there shouldn't be too hard once we get a clear understanding on how things works. Taking a look at python wrapper might help. Since xgboost's wrapper only exposes C functions whose type should have been well defined in JNI

**Comment by yanqingmen** [comment]
hi, @tqchen 

I've made a pure JNI based wrapper and opened a pull request.
if any modification needed, feel free to inform me~

**Comment by tqchen** [comment]
Great! I have made some comments, thanks for doing this. I am sure it is going to be very useful

**Comment by yanqingmen** [comment]
hi, @tqchen

I tried to write some example code for xgboost4j and I got some problem.   
In my past works, I always use python to pre-process data and transfer them into libsvm-style format and then DMatrix can handle them easily.   
But when I try to do data pre-processing in pure java from scratch, I found it is really trivial and not clean enough. I think I may need to found some third party toolkit to help me processing matrix-style data in java (only in example code), but I'm not sure this is what we intended to do ~ 
Do you have any advice for me?

thanks a lot

**Comment by tqchen** [comment]
Hi @yanqingmen I think we are fine to start from basic dense matrix (either float[] plus nrow, ncol, or float[][] )and optionally sparse matrix. Most existing packages should have interface to these two data structures, and worry about such things latter:)

I assume parsing from csv file into these data structure should not be a big problem

**Comment by yanqingmen** [comment]
ok, no problem, maybe I have worried about something too far away.

**Comment by tqchen** [comment]
@yanqingmen Thanks for doing this. Hope we can continue to get your help to make xgboost better.

 Do you have a weibo account that I could mention you on? You can send me an email on this.

Thanks

**Comment by yanqingmen** [comment]
ok, my weibo account "掩青门", I've follewed you :)

**Comment by yanqingmen** [comment]
my email: toofooltosay@gmail.com
